plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'ai.camelid.remote.crypto.expo'
version = '0.1.0'

android {
  namespace "ai.camelid.remote.crypto.expo"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }
  lintOptions {
    abortOnError false
  }
  sourceSets {
    main {
      jniLibs.srcDirs = ['src/main/jniLibs']
    }
  }
}

dependencies {
  implementation 'net.java.dev.jna:jna:5.19.1@aar'
  androidTestImplementation 'androidx.test.ext:junit:1.2.1'
  androidTestImplementation 'androidx.test:runner:1.6.2'
  androidTestImplementation 'androidx.test:core:1.6.1'
}
